name: Build EXE and Upload to Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --name domain93 domain93/__main__.py

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/domain93.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
